version: '3.9'

services:
  app:
    build: .
    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - 8000:80
    restart: always